# Makefile specific to the strategy.
# All strategies have a common process that can be further embelished.
# The common process is encapsulated in a makefile that lives in the parent directory.
include ../strategy.mk
